# Generated by Django 2.2.2 on 2019-10-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('thumbs', models.CharField(max_length=10)),
            ],
        ),
    ]
