# Generated by Django 2.2.2 on 2019-10-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
